"""add_parsed_pages

Revision ID: dde708c6296e
Revises: 800c31780fbb
Create Date: 2026-06-18 01:42:31.365139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dde708c6296e'
down_revision: Union[str, Sequence[str], None] = '800c31780fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_pages_id'), 'parsed_pages', ['id'], unique=False)
    op.create_index(op.f('ix_parsed_pages_url'), 'parsed_pages', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_pages_url'), table_name='parsed_pages')
    op.drop_index(op.f('ix_parsed_pages_id'), table_name='parsed_pages')
    op.drop_table('parsed_pages')
    # ### end Alembic commands ###
